### ISSUE TITLE
copyFromMyProject example

### ISSUE THREAD

**Issue by abushoy** [sbg/okAPI#4]
Hello, 

source_file is not defined  in the  example  
https://github.com/sbg/okAPI/blob/master/Recipes/SBPLAT/files_copyFromMyProject.ipynb

Thank you, Alla

**Comment by jackDiGi** [comment]
Thanks Alla,

I just fixed this and committed the updated Recipe.

Have a great weekend,

Jack

**Comment by abushoy** [comment]
Thank you Jack
